server:
  port: 8000

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: http://studentsvc.student-service:8081
          predicates:
            - Path=/slot/**

        - id: student-service
          uri: http://studentsvc.student-service:8081
          predicates:
            - Path=/student/**

        - id: book-service
          uri: http://booksvc.book-namespace.com:8082
          predicates:
            - Path=/books/**